### ISSUE TITLE
[Bug]: The CSS seems broken in the demo

### ISSUE THREAD

**Issue by RoneoOrg** [CloudWithChris/hugo-creator#85]
### What happened?

See https://hugo-creator.cloudwithchris.com/

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by chrisreddington** [comment]
Thanks @RoneoOrg - I noticed this earlier as well! I have a suspicion on what this is, so will have a glance tomorrow.

Appreciate you flagging this!

**Comment by chrisreddington** [comment]
@RoneoOrg - In the meantime, if you wanted to see an example - Please see www.cloudwithchris.com :)

**Comment by chrisreddington** [comment]
@RoneoOrg - I have now fixed this. Admittedly the colours look terrible (deliberately I might add! As I was trying to show that the SASS variables work for adjusting the theme colour).

Will close this issue now, but thanks again for taking the time to flag this. I appreciate it :)
