### ISSUE TITLE
[Feature]: How To use Archetype and create a nice list

### ISSUE THREAD

**Issue by fskelly** [CloudWithChris/hugo-creator#95]
### Provide a general summary of the suggestion

Looking to extend your idea with "persons" archetype and modify for author and then provide a list of Authors and authored blog posts.

I use a "post" archetype and looking to understand HUGO more to create an Author list page

### Context

Would be nice to understand how it works so that other archetypes can used and create our own lists.

### Your Environment

Hugo Extended
Testing with bootstrap theme
Happy to share content

**Comment by chrisreddington** [comment]
Hey @fskelly - I think you'd be wanting to replicate something [similar to this](https://github.com/CloudWithChris/hugo-creator/blob/main/layouts/person/single.html#L51-L78).

Hugo Creator is a custom theme that uses the data *from* archetypes in the layouts to generate the appropriate views. So, if I wanted to enhance the theme to also show posts, then I would need to update it to find pages in blogs that intersect the authors property (or whichever property lists the user in the blog archetype.

So for example, [these lines in the blog archetype](https://github.com/CloudWithChris/hugo-creator/blob/main/archetypes/blog/index.md?plain=1#L22-L23) are the default generated for authors, so to extend hugo-creator, it'd likely want to be something like the below in [the person's profile page](https://github.com/CloudWithChris/hugo-creator/blob/main/layouts/person/single.htm).

`
    {{ $blogs:= where (where (where .Site.RegularPages "Type" "in" "blog") ".Params.upcoming" "!=" true) ".Params.authors" "intersect" (slice $.File.ContentBaseName) }}

    {{ if gt (len $blogs) 0}}
      <h2>Blogs</h2>
      {{- range $blogs -}}
        {{- partial "cards/content-card.html" (dict "content" .) -}}
      {{ end }}
    {{ end}}
`
